name: CI (bento) x64

on:
  workflow_dispatch:

jobs:

  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "arch=x64"
    - "engflow-cluster=local"
    - "engflow-bento-name=mybento-x64"
    - "engflow-bento-allow-save=true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run presubmit checks
      run: |
        bazel test //...
