name: bazel (bento)

on:
  workflow_dispatch:

jobs:

  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "arch=x64"
    - "engflow-cluster=local"
    - "engflow-bento-name=mybento-x64"
    - "engflow-bento-allow-save=true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run bazel
      run: |
        bazel info
